/* AUTOGENERATED FILE - BUT MANUALLY UPDATED FOR PRODUCTION FIX */

export const projectId = "odcgnzfremrqnvtitpcc";

// Key from environment variables (Vite)
// IMPORTANT:
// - Frontend only receives env vars prefixed with VITE_
// - Do NOT use service_role in frontend
const rawAnonKey =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ||
  (import.meta.env.VITE_SUPABASE_PUBLIC_ANON_KEY as string | undefined) ||
  (import.meta.env.VITE_SUPABASE_KEY as string | undefined) ||
  "";

export const publicAnonKey = rawAnonKey
  .trim()
  .replace(/^Bearer\s+/i, '');

// ✅ Validação: Avisar se a chave estiver faltando
if (!publicAnonKey) {
  console.error(
    "❌ ERRO CRÍTICO: VITE_SUPABASE_ANON_KEY não configurada!\n" +
    "Configure a variável de ambiente VITE_SUPABASE_ANON_KEY no Vercel/Netlify\n" +
    "Ou adicione no arquivo .env.local para desenvolvimento local"
  );
}

// Placeholder comum (evita confusão de 401)
if (publicAnonKey && /^<.*>$/.test(publicAnonKey)) {
  console.error(
    "❌ ERRO CRÍTICO: VITE_SUPABASE_ANON_KEY está com placeholder (ex.: <SUPABASE_ANON_KEY>).\n" +
    "Substitua pelo valor real (Settings → API → anon public key) do projeto odcgnzfremrqnvtitpcc."
  );
}
