/* AUTOGENERATED FILE - BUT MANUALLY UPDATED FOR PRODUCTION FIX */

export const projectId = "odcgnzfremrqnvtitpcc";

// Key from environment variables (Vite)
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
