/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_67caf26a (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/uknccixtubkdkofyieie/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";
import {
  SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_URL,
} from "./utils-env.ts";

const client = () =>
  createClient(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
  );

// Set stores a key-value pair in the database.
// ✅ CORRIGIDO: A tabela TEM created_at e updated_at - usar DEFAULT NOW() do banco
// 🚫 VALIDAÇÃO: Previne uso indevido de KV Store para dados críticos
export const set = async (key: string, value: any): Promise<void> => {
  // ✅ Validar uso de KV Store (previne dados críticos em KV Store)
  // 🚫 REGRA: KV Store APENAS para cache temporário (veja REGRA_KV_STORE_VS_SQL.md)
  const criticalPatterns = [
    /^user:/i,
    /^session:/i,
    /^conversation:/i,
    /^message:/i,
    /^reservation:/i,
    /^property:/i,
    /^listing:/i,
    /^organization:/i,
    /^org:/i,
    /^config:/i,
    /^channel_config:/i,
    /^acc:/i,
    /^res:/i,
    /^guest:/i,
    /^booking:/i,
    /chat:conversation:/i,
    /chat:message:/i,
  ];
  
  const isCritical = criticalPatterns.some(pattern => pattern.test(key));
  if (isCritical) {
    const allowedPrefixes = ['cache:', 'process:', 'temp:', 'lock:', 'queue:'];
    const hasAllowedPrefix = allowedPrefixes.some(prefix => key.startsWith(prefix));
    
    if (!hasAllowedPrefix) {
      throw new Error(
        `❌ PROIBIDO: Não use KV Store para dados críticos!\n` +
        `   Key: ${key}\n` +
        `   REGRA: KV Store APENAS para cache temporário (TTL < 24h)\n` +
        `   SOLUÇÃO: Use tabela SQL apropriada (users, conversations, messages, etc)\n` +
        `   📚 Veja: REGRA_KV_STORE_VS_SQL.md\n` +
        `   ✅ Prefixos permitidos: cache:*, process:*, temp:*, lock:*, queue:*`
      );
    }
  }
  
  const supabase = client()
  // ✅ CORRIGIDO: Especificar updated_at explicitamente para evitar erro de trigger
  // Para INSERT, created_at e updated_at usam DEFAULT NOW()
  // Para UPDATE, updated_at é atualizado pela trigger, mas especificamos aqui também para garantir
  const { error } = await supabase.from("kv_store_67caf26a").upsert({
    key,
    value,
    updated_at: new Date().toISOString()
    // created_at não especificamos - deixa o banco usar DEFAULT NOW() apenas no INSERT
  }, {
    onConflict: 'key'
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_67caf26a").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_67caf26a").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
// ✅ CORRIGIDO: Especificar updated_at explicitamente para evitar erro de trigger
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_67caf26a").upsert(
    keys.map((k, i) => ({ 
      key: k, 
      value: values[i],
      updated_at: new Date().toISOString()
      // created_at não especificamos - deixa o banco usar DEFAULT NOW() apenas no INSERT
    })),
    {
      onConflict: 'key'
    }
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_67caf26a").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_67caf26a").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_67caf26a").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Get Supabase client for direct database operations
export const getSupabaseClient = () => {
  return createClient(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY
  );
};
